# Generated by Django 3.0.6 on 2020-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200526_1450'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('article_title', 'article_version'), name='one_title_many_versions'),
        ),
    ]
