# Generated by Django 3.0.6 on 2020-05-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200526_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.TextField(verbose_name='Article text')),
            ],
        ),
    ]
