# Generated by Django 3.0.6 on 2020-06-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200528_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleversion',
            options={'get_latest_by': 'version', 'verbose_name_plural': 'Article versions'},
        ),
    ]
